### ISSUE TITLE
compiling issues on Debian 12

### ISSUE THREAD

**Issue by sparky4** [Mellvik/TLVC#49]
sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body -c -o super.o super.c
super.c:19:28: fatal error: linuxmt/devnum.h: No such file or directory
 #include <linuxmt/devnum.h>

ls: cannot access 'tlvc/include/linuxmt/dev*': No such file or directory

the file dose not exist

**Comment by sparky4** [comment]
copied and found another seperate issue with compiling

ia16-elf-gcc -ffreestanding -fno-inline -melks -mcmodel=small -msegment-relocation-stuff   -I/home/sparky4/p/TLVC/include -I/home/sparky4/p/TLVC/tlvc/include -I/home/sparky4/p/TLVC/libc/include -D__KERNEL__ -Os -fno-delete-null-pointer-checks -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body -c -o rd.o rd.c
rd.c:266:6: error: conflicting named address spaces (generic vs __far) for ‘rd_init’
 void rd_init(void)
      ^~~~~~~
In file included from /home/sparky4/p/TLVC/tlvc/include/arch/system.h:5:0,
                 from /home/sparky4/p/TLVC/tlvc/include/linuxmt/ntty.h:65,
                 from /home/sparky4/p/TLVC/tlvc/include/linuxmt/sched.h:11,
                 from blk.h:5,
                 from rd.c:29:
/home/sparky4/p/TLVC/tlvc/include/linuxmt/init.h:48:22: note: previous declaration of ‘rd_init’ was here
 extern void INITPROC rd_init(void);
                      ^~~~~~~
make[3]: *** [../../../../Makefile-rules:260: rd.o] Error 1
make[3]: Leaving directory '/home/sparky4/p/TLVC/tlvc/arch/i86/drivers/block'
make[2]: *** [Makefile:195: drivers/block/blk_drv.a] Error 2
make[2]: Leaving directory '/home/sparky4/p/TLVC/tlvc/arch/i86'
make[1]: *** [Makefile:75: Image] Error 2
make[1]: Leaving directory '/home/sparky4/p/TLVC/tlvc'
make: *** [Makefile:13: all] Error 2
Build script has terminated with error 5

**Comment by sparky4** [comment]
fixed by adding __far in rd.c to void rd_init(void);
so it is now void __far rd_init(void);

**Comment by sparky4** [comment]
ia16-elf-gcc -E -traditional -I/home/sparky4/p/TLVC/include -I/home/sparky4/p/TLVC/tlvc/include -I/home/sparky4/p/TLVC/libc/include -D__KERNEL__ -o boot/crt0.tmp boot/crt0.S
ia16-elf-as   --32-segelf -o boot/crt0.o boot/crt0.tmp
rm boot/crt0.tmp
(cd ../.. ; ia16-elf-ld.gold  -M  -T /home/sparky4/p/TLVC/tlvc/elks-small.ld \
	arch/i86/boot/crt0.o \
	init/main.o '-(' fs/fs.a kernel/kernel.a lib/lib.a net/net.a fs/minix/minixfs.a fs/msdos/msdos.a arch/i86/kernel/akernel.a arch/i86/lib/lib86.a arch/i86/mm/mm.a  arch/i86/drivers/char/chr_drv.a arch/i86/drivers/block/blk_drv.a arch/i86/drivers/net/net_drv.a '-)' "`ia16-elf-gcc -ffreestanding -fno-inline -melks -mcmodel=small -msegment-relocation-stuff   -I/home/sparky4/p/TLVC/include -I/home/sparky4/p/TLVC/tlvc/include -I/home/sparky4/p/TLVC/libc/include -D__KERNEL__ -Os -fno-delete-null-pointer-checks -Wnull-dereference -Wall -W -Wmissing-prototypes -Wpointer-arith -Wreturn-type -Wredundant-decls -Wuninitialized -Winline -Wswitch -Wshadow -Wchar-subscripts -Wwrite-strings -Wdiscarded-qualifiers -Wcast-align -Wcast-qual -Wno-sign-compare -Wno-cast-qual -Wno-unused-parameter -Wno-missing-prototypes -Wno-empty-body -print-libgcc-file-name`" \
	-o arch/i86/boot/system > arch/i86/boot/system-full.map ; \
	ia16-elf-nm arch/i86/boot/system | sed -e '/&/d; /!/d' | sort > \
		arch/i86/boot/system.map; \
	elf2elks --symfile arch/i86/boot/system.sym arch/i86/boot/system)
arch/i86/drivers/block/blk_drv.a(bioshd.o):function bioshd_init: error: undefined reference to 'copy_fdpt'
arch/i86/drivers/block/blk_drv.a(bioshd.o):function bioshd_init: error: undefined reference to 'copy_fdpt!'
ia16-elf-nm: 'arch/i86/boot/system': No such file
elf2elks: error: cannot open input file `arch/i86/boot/system': No such file or directory
make[2]: *** [Makefile:131: boot/system] Error 1
make[2]: Leaving directory '/home/sparky4/p/TLVC/tlvc/arch/i86'
make[1]: *** [Makefile:75: Image] Error 2
make[1]: Leaving directory '/home/sparky4/p/TLVC/tlvc'
make: *** [Makefile:13: all] Error 2
Build script has terminated with error 5


well shoot...

i dont know how to fix this system issue

**Comment by sparky4** [comment]
oh wait let me make prototype for missing functions

**Comment by sparky4** [comment]
commended out the function in tlvc/arch/i86/drivers/block/bioshd.c

it compiled..... :D lets see if it works

**Comment by sparky4** [comment]
works hope this helps

**Comment by Mellvik** [comment]
Thanks, @sparky4 - this is great! Running on more platforms (mac gas been dominant recently)
And selecting devices that haven't been used for a while (like ramdisk which I've never used...).
TLVC works best with direct i/o, i.e. no bios i/o. If you need to run bios i/o, make sure you use the updates pushed earlier today.

**Comment by Mellvik** [comment]
I will have a close look at your findings in the morning.

**Comment by Mellvik** [comment]
> commended out the function in tlvc/arch/i86/drivers/block/bioshd.c
> 
> it compiled..... :D lets see if it works

Oooops, that was a leftover from testing earlier today. Bummer. Will push a fix for that and a couple of other small issues asap.

**Comment by sparky4** [comment]
np np
